// Generated by tools/generate_oit_shader.py. Do not edit.
#[vertex]
#version 450
#define OUTPUT_IS_SRGB false
#define mold_msaa_enabled false
#define FRAGCOORD gl_FragCoord
#define INSTANCE_ID gl_InstanceIndex
#define emission_strength mold_flags.x
#define angular_data lod_data.zw
layout(set=0,binding=0,std430) readonly buffer Vertices { vec4 mesh_data[]; };
layout(set=0,binding=1,std430) readonly buffer Instances { vec4 instance_data[]; };
layout(set=0,binding=2,std140) uniform Camera { mat4 PROJECTION_MATRIX; mat4 VIEW_MATRIX; mat4 INV_VIEW_MATRIX; vec4 viewport; };
#define mold_viewport_size viewport.xy
#define VIEWPORT_SIZE mold_viewport_size

layout(set=0,binding=6,std140) uniform Appearance { vec4 appearance_values[8]; };
#define _PencilAngle appearance_values[0][0]
#define _PencilCrosshatch appearance_values[0][1]
#define _PencilHatchScale appearance_values[0][2]
#define _PencilHatching appearance_values[0][3]
#define _PencilLength appearance_values[1][0]
#define _PencilPaperScale appearance_values[1][1]
#define _PencilPaperSeed appearance_values[1][2]
#define _PencilPressure appearance_values[1][3]
#define _PencilRoughness appearance_values[2][0]
#define _PencilSeed appearance_values[2][1]
#define _PencilSide appearance_values[2][2]
#define _PencilSmudge appearance_values[2][3]
#define _PencilSoftness appearance_values[3][0]
#define _PencilSurfaceScale appearance_values[3][1]
#define _PencilTaper appearance_values[3][2]
#define _PencilPaperColor appearance_values[4]
#define _PencilPaperOrigin appearance_values[5]
#define _PencilPaperU appearance_values[6]
#define _PencilPaperV appearance_values[7]
vec4 primary_color;
vec4 secondary_color;
vec4 shape_data;
vec4 dash_data;
vec4 mold_flags;
vec4 gradient_data;
vec4 lod_data;
layout(location=7) out vec4 mold_line_values;
layout(location=8) out vec2 mold_gradient_and_coverage;
layout(location=9) out vec4 mold_polyline_coord;
layout(location=10) out vec4 mold_vertex_color;
layout(location=11) out vec3 mold_effect_position;
layout(location=0) flat out int oit_instance_id;
layout(location=18) out vec2 UV;

layout(set=0,binding=5,std430) readonly buffer Matrices { mat4 prepared_matrices[]; };
vec3 VERTEX,NORMAL; vec2 UV2; vec4 COLOR,CUSTOM0,CUSTOM1,CUSTOM2,CUSTOM3,POSITION; mat4 MODEL_MATRIX,MODELVIEW_MATRIX;
const float MOLD_TAU = 6.28318530718;
const float MOLD_TORUS_BASE_MAJOR_RADIUS = 0.375;
const float MOLD_TORUS_BASE_TUBE_RADIUS = 0.125;
const float MOLD_AA_PADDING_PIXELS = 1.0;
bool mold_stroke_start(int id) {
    int corner[6] = int[6](0,1,2,0,2,3);
    int index = id % 6;
    if (id >= 6 && id < 12) { if (index % 3 == 1) index += 1; else if (index % 3 == 2) index -= 1; }
    return id < 12 ? corner[index] < 2 : id < 24;
}
vec2 mold_gpu_dir(vec2 delta, vec2 fallback) {
    float size = length(delta);
    return size > 0.00001 ? delta / size : fallback;
}
vec2 mold_gpu_normal(vec2 direction) { return vec2(-direction.y, direction.x); }
float mold_gpu_cross(vec2 a, vec2 b) { return a.x*b.y-a.y*b.x; }
vec2 mold_gpu_outline(vec2 incoming, vec2 outgoing, vec2 normal, float side,
        float radius, float neighbor, bool endpoint, int local_mold_gpu_join, float local_mold_gpu_miter_limit) {
    if (endpoint || (local_mold_gpu_join != 0 && mold_gpu_cross(incoming,outgoing)*side < 0.0))
        return normal * side * radius;
    vec2 sum = mold_gpu_normal(incoming) + mold_gpu_normal(outgoing);
    float denominator = dot(sum, mold_gpu_normal(outgoing));
    if (abs(denominator) < 0.00001) return normal * side * radius;
    vec2 offset = sum * (side * radius / denominator);
    float limit = min(radius * local_mold_gpu_miter_limit, neighbor * 0.5 + radius);
    return length(offset) > limit ? normalize(offset)*limit : offset;
}
void mold_stroke_vertex(vec4 previous, vec4 a, vec4 b, vec4 next, vec4 metrics,
        int local_id, int local_mold_gpu_join, int local_mold_gpu_cap, float local_mold_gpu_miter_limit,
        out vec3 position, out vec2 uv, out vec4 custom0, out vec4 custom1, out vec4 custom2) {
    int flags = int(round(metrics.x));
    bool first = (flags & 1) != 0;
    bool last = (flags & 2) != 0;
    vec2 direction = mold_gpu_dir(b.xy-a.xy, vec2(1.0,0.0));
    vec2 incoming = first ? direction : mold_gpu_dir(a.xy-previous.xy,direction);
    vec2 outgoing = last ? direction : mold_gpu_dir(next.xy-b.xy,direction);
    vec2 normal = mold_gpu_normal(direction);
    float segment_length = length(b.xy-a.xy);
    float progress = metrics.y / max(metrics.w,0.00001);
    position = a.xyz;
    uv = vec2(progress,0.5);
    custom0 = vec4(0.0,0.0,0.0,max(a.w*0.5,0.00001));
    custom1 = vec4(0.0); custom2 = vec4(0.0);
    int corners[6] = int[6](0,1,2,0,2,3);
    if (local_id < 12) {
        float side = local_id < 6 ? 1.0 : -1.0;
        int corner_id = local_id % 6;
        if (side < 0.0) { if (corner_id % 3 == 1) corner_id += 1; else if (corner_id % 3 == 2) corner_id -= 1; }
        int corner = corners[corner_id];
        bool at_start = corner < 2;
        bool outline = corner == 1 || corner == 2;
        vec4 current = at_start ? a : b;
        float radius = max(current.w*0.5,0.00001);
        vec2 offset = vec2(0.0);
        if (outline) offset = at_start
            ? mold_gpu_outline(incoming,direction,normal,side,radius,min(length(a.xy-previous.xy),segment_length),first,local_mold_gpu_join,local_mold_gpu_miter_limit)
            : mold_gpu_outline(direction,outgoing,normal,side,radius,min(length(next.xy-b.xy),segment_length),last,local_mold_gpu_join,local_mold_gpu_miter_limit);
        vec2 start_shift = first && local_mold_gpu_cap == 1 ? -direction*a.w*0.5 : vec2(0.0);
        vec2 end_shift = last && local_mold_gpu_cap == 1 ? direction*b.w*0.5 : vec2(0.0);
        vec2 shift = at_start ? start_shift : end_shift;
        float line_length = segment_length + length(start_shift)+length(end_shift);
        bool start_cap = first && local_mold_gpu_cap != 2;
        bool end_cap = last && local_mold_gpu_cap != 2;
        vec2 extrusion = offset;
        if (at_start && start_cap) extrusion -= direction*radius;
        if (!at_start && end_cap) extrusion += direction*radius;
        float x = (at_start ? 0.0 : line_length)+dot(offset,direction);
        float y = dot(offset,normal)/radius;
        custom0 = vec4(extrusion,0.0,radius);
        custom1 = vec4(normal.x,y,start_cap ? 1.0-x/radius : 0.0,end_cap ? 1.0-(line_length-x)/radius : 0.0);
        custom2 = vec4(normal.y,dot(extrusion,normal)/radius,start_cap ? -dot(extrusion,direction)/radius : 0.0,end_cap ? dot(extrusion,direction)/radius : 0.0);
        position = current.xyz+vec3(offset+shift,0.0);
        progress = clamp((at_start ? metrics.y : metrics.z)+dot(offset,direction),metrics.y,metrics.z)/max(metrics.w,0.00001);
        uv = vec2(progress,0.5-y*0.5);
    } else {
        bool at_start = local_id < 24;
        int decoration_id = (local_id-12) % 12;
        vec4 current = at_start ? a : b;
        position = current.xyz;
        float radius = max(current.w*0.5,0.00001);
        bool endpoint = at_start ? first : last;
        bool mold_active = endpoint ? local_mold_gpu_cap == 2 : at_start && local_mold_gpu_join != 0;
        float turn = mold_gpu_cross(incoming,direction);
        float side = turn > 0.0 ? -1.0 : 1.0;
        vec2 from = endpoint ? (at_start ? normal : -normal) : mold_gpu_normal(incoming)*side;
        vec2 to = endpoint ? -from : normal*side;
        vec2 offset = vec2(0.0);
        bool round_join = endpoint || local_mold_gpu_join == 2;
        if (mold_active && (endpoint || abs(turn)>0.00001)) {
            if (round_join) {
                float start_angle = atan(from.y,from.x);
                float delta = endpoint ? 3.14159265359 : atan(mold_gpu_cross(from,to),dot(from,to));
                int steps = abs(delta) > 1.57080632679 ? 2 : 1;
                int step_id = decoration_id/6;
                if (step_id < steps) {
                    float angle_a = start_angle+delta*float(step_id)/float(steps);
                    float angle_b = start_angle+delta*float(step_id+1)/float(steps);
                    int corner_id = decoration_id%6;
                    if (delta > 0.0) { if (corner_id%3==1) corner_id+=1; else if (corner_id%3==2) corner_id-=1; }
                    int corner = corners[corner_id];
                    if (corner==1) offset=vec2(cos(angle_a),sin(angle_a));
                    if (corner==2) offset=vec2(cos((angle_a+angle_b)*0.5),sin((angle_a+angle_b)*0.5))/cos((angle_b-angle_a)*0.5);
                    if (corner==3) offset=vec2(cos(angle_b),sin(angle_b));
                }
                custom1=vec4(offset,0.0,0.0); custom2=custom1;
            } else {
                int corner=decoration_id;
                if (turn > 0.0) { if(corner==1) corner=2; else if(corner==2) corner=1; }
                if(corner==1) offset=from; else if(corner==2) offset=to;
                vec2 axis=mold_gpu_dir(from+to,normal);
                vec2 bevel_axis=axis/max(dot(axis,from),0.00001);
                custom1=vec4(0.0,dot(offset,bevel_axis),0.0,0.0); custom2=custom1;
            }
        }
        custom0=vec4(offset*radius,round_join ? 2.0 : 1.0,radius);
        position+=vec3(offset*radius,0.0);
        progress=(at_start ? metrics.y : metrics.z)/max(metrics.w,0.00001);
        uv=vec2(progress,0.5-(length(offset)>0.00001 ? dot(normalize(offset),normal)*0.5 : 0.0));
    }
}
void mold_billboard_vertex(vec4 previous, vec4 a, vec4 b, vec4 next, vec4 metrics,
        int id, int join_mode, int cap_mode, float miter_limit, mat4 model_view,
        float width_scale, bool perspective, float near_plane,
        out vec3 position, out vec2 uv, out vec4 c0, out vec4 c1, out vec4 c2) {
    previous.xyz = (model_view * vec4(previous.xyz,1.0)).xyz;
    a.xyz = (model_view * vec4(a.xyz,1.0)).xyz;
    b.xyz = (model_view * vec4(b.xyz,1.0)).xyz;
    next.xyz = (model_view * vec4(next.xyz,1.0)).xyz;
    float clip_z = -max(near_plane,0.0001);
    bool hidden = a.z > clip_z && b.z > clip_z;
    if (!hidden) {
        if (a.z > clip_z) { a = mix(a,b,(clip_z-a.z)/(b.z-a.z)); previous = a; metrics.x = float(int(metrics.x)|1); }
        if (b.z > clip_z) { b = mix(b,a,(clip_z-b.z)/(a.z-b.z)); next = b; metrics.x = float(int(metrics.x)|2); }
    }
    vec3 center = mold_stroke_start(id) ? a.xyz : b.xyz;
    float depth = max(-center.z, max(near_plane,0.0001));
    if (perspective) {
        previous.xy *= depth/max(-previous.z,max(near_plane,0.0001));
        a.xy *= depth/max(-a.z,max(near_plane,0.0001));
        b.xy *= depth/max(-b.z,max(near_plane,0.0001));
        next.xy *= depth/max(-next.z,max(near_plane,0.0001));
        a.w *= depth/max(-a.z,max(near_plane,0.0001));
        b.w *= depth/max(-b.z,max(near_plane,0.0001));
    }
    a.w *= width_scale; b.w *= width_scale;
    vec2 projected_center = mold_stroke_start(id) ? a.xy : b.xy;
    mold_stroke_vertex(previous,a,b,next,metrics,id,join_mode,cap_mode,miter_limit,position,uv,c0,c1,c2);
    position = center + vec3(position.xy-projected_center,0.0);
    if (hidden) { position = vec3(0.0,0.0,1.0); c0 = vec4(0.0); }
}
float mold_stroke_near(mat4 projection) {
    mat4 inv = inverse(projection);
    vec4 a = inv*vec4(0.0,0.0,1.0,1.0);
    vec4 b = inv*vec4(0.0,0.0,-1.0,1.0);
    return min(abs(a.z/a.w),abs(b.z/b.w));
}
void mold_deform_rounded(vec4 shape, vec4 direction, inout vec3 vertex, inout vec3 normal) {
    if (shape.x > 3.5) {
        float aspect = max(shape.z, 1e-20);
        float apothem = 0.5 * shape.w;
        float slant = length(vec2(aspect, apothem));
        float center_height = apothem / (slant + apothem);
        vec3 scale = vec3(1.0, aspect, 1.0);
        vec3 support = vertex * 2.0 - direction.xyz * 0.5;
        vec3 sphere_normal = normalize(direction.xyz / scale);
        vec3 incenter = vec3(0.0, -0.5 + center_height, 0.0);
        vec3 radius = vec3(aspect * center_height, center_height, aspect * center_height);
        vertex = mix(support, incenter, shape.y) + sphere_normal * radius * shape.y;
        normal = normalize(direction.xyz);
        return;
    }
    vec3 radii = shape.yzw;
    vec3 center = vertex - direction.xyz * 0.25;
    vertex = center * (vec3(2.0) - 4.0 * radii) + direction.xyz * radii;
    vec3 safe_radii = max(radii, vec3(1e-30));
    float smallest = min(safe_radii.x, min(safe_radii.y, safe_radii.z));
    normal = normalize(direction.xyz * (smallest / safe_radii));
}
int mold_local_aa_quality() {
 int flags = int(round(mold_flags.w));
 return (flags & 1) == 0 ? 0 : ((flags & 32) != 0 ? 2 : 1);
}
float projected_pixel_distance(vec4 from_clip, vec4 to_clip, vec2 viewport_size) {
 vec2 from_ndc = from_clip.xy / max(abs(from_clip.w), 0.00001);
 vec2 to_ndc = to_clip.xy / max(abs(to_clip.w), 0.00001);
 return length((to_ndc - from_ndc) * viewport_size * 0.5);
}
float mold_polyline_raster_scale(vec3 position, vec4 c0, vec4 c1, vec4 c2,
        mat4 model_view, mat4 projection, vec2 viewport, float padding_pixels,
        out float pixel_coverage) {
    vec2 extrusion = c0.xy;
    float radius = c0.w;
    bool is_segment = c0.z < 0.5;
    vec2 width_direction = is_segment ? vec2(c1.x, c2.x)
        : extrusion / max(length(extrusion), 0.00001);
    vec4 center_clip = projection * model_view * vec4(position, 1.0);
    vec4 edge_clip = projection * model_view
        * vec4(position + vec3(width_direction * radius, 0.0), 1.0);
    float half_width_pixels = projected_pixel_distance(center_clip, edge_clip, viewport);
    float target_width_pixels = half_width_pixels * 2.0;
    pixel_coverage = target_width_pixels;
    float raster_width_pixels = max(1.0, target_width_pixels + padding_pixels * 2.0);
    return target_width_pixels > 0.0 ? raster_width_pixels / target_width_pixels : 1.0;
}
float mold_spatial_line_raster_scale(float progress, mat4 model, mat4 view,
        mat4 projection, vec2 viewport, out float pixel_coverage) {
    vec3 center_view = (view * model[3]).xyz;
    vec3 line_axis_view = (view * vec4(model[1].xyz, 0.0)).xyz;
    vec3 width_x_view = (view * vec4(model[0].xyz, 0.0)).xyz;
    vec3 width_z_view = (view * vec4(model[2].xyz, 0.0)).xyz;
    vec3 anchor_view = center_view + line_axis_view * (progress - 0.5);
    vec3 view_direction = projection[3][3] > 0.5
        ? vec3(0.0, 0.0, -1.0) : anchor_view;
    vec3 screen_normal_view = cross(view_direction, line_axis_view);
    float normal_length = length(screen_normal_view);
    if (normal_length < 0.00001) {
        screen_normal_view = cross(vec3(0.0, 0.0, -1.0), line_axis_view);
        normal_length = length(screen_normal_view);
    }
    screen_normal_view = normal_length < 0.00001
        ? vec3(1.0, 0.0, 0.0) : screen_normal_view / normal_length;
    float target_diameter = max(length(width_x_view), length(width_z_view));
    vec4 anchor_clip = projection * vec4(anchor_view, 1.0);
    float target_width_pixels = projected_pixel_distance(anchor_clip,
        projection * vec4(anchor_view + screen_normal_view * target_diameter, 1.0), viewport);
    pixel_coverage = target_width_pixels;
    return max(target_width_pixels, 1.0) / max(target_width_pixels, 0.00001);
}
int packed_gradient(int divisor, int modulus) {
 return (int(round(gradient_data.w)) / divisor) % modulus;
}
void main() {
 oit_instance_id=gl_InstanceIndex;
 int v=gl_VertexIndex*8; VERTEX=mesh_data[v].xyz; NORMAL=mesh_data[v+1].xyz;
 UV=mesh_data[v+2].xy; UV2=mesh_data[v+2].zw; COLOR=mesh_data[v+3];
 CUSTOM0=mesh_data[v+4];CUSTOM1=mesh_data[v+5];CUSTOM2=mesh_data[v+6];CUSTOM3=mesh_data[v+7];
 MODEL_MATRIX=prepared_matrices[gl_InstanceIndex*2];
 MODELVIEW_MATRIX=prepared_matrices[gl_InstanceIndex*2+1];
 int j=5+int(instance_data[4].x)*3+gl_InstanceIndex*7;
 if ((int(round(instance_data[j+4].w)) & 4096) != 0) { CUSTOM0=vec4(0); CUSTOM1=vec4(0); CUSTOM2=vec4(0); CUSTOM3=vec4(0); UV2=vec2(0); }

    vec3 mold_author_position = VERTEX;
    bool mold_is_billboard = UV.x >= 8192.0;
    vec4 mold_custom0 = CUSTOM0, mold_custom1 = CUSTOM1, mold_custom2 = CUSTOM2;
    if (UV.x >= 8192.0) {
        int config = int(round(UV.x)) / 64 - 128;
        vec4 a = vec4(CUSTOM1.xyz,CUSTOM0.w), b = vec4(CUSTOM2.xyz,CUSTOM1.w);
        mold_author_position = mold_stroke_start(int(round(UV.x)) & 63) ? a.xyz : b.xyz;
        vec4 metrics = vec4(float(config & 3),UV.y,UV2.x,UV2.y);
        float scale = max(length(MODEL_MATRIX[0].xyz),max(length(MODEL_MATRIX[1].xyz),length(MODEL_MATRIX[2].xyz)));
        mold_billboard_vertex(vec4(VERTEX,0.0),a,b,vec4(CUSTOM0.xyz,0.0),metrics,int(round(UV.x)) & 63,
            (config >> 2) & 3,(config >> 4) & 3,CUSTOM2.w,MODELVIEW_MATRIX,scale,
            abs(PROJECTION_MATRIX[3][3]) < 0.5,mold_stroke_near(PROJECTION_MATRIX),VERTEX,UV,mold_custom0,mold_custom1,mold_custom2);
        MODELVIEW_MATRIX = mat4(1.0);
        NORMAL = vec3(0.0,0.0,1.0);
    }
    primary_color = instance_data[j+0];
    secondary_color = instance_data[j+1];
    shape_data = instance_data[j+2];
    dash_data = instance_data[j+3];
    mold_flags = instance_data[j+4];
    gradient_data = instance_data[j+5];
    lod_data = instance_data[j+6];
    mold_vertex_color = ((int(round(mold_flags.w)) & 8) != 0) ? CUSTOM3 : COLOR;
    if ((mold_flags.z > 2.5)) mold_deform_rounded(shape_data, CUSTOM0, VERTEX, NORMAL);
    mold_gradient_and_coverage.y = 0.0;
    if ((mold_flags.z > 0.5 && mold_flags.z < 1.5)) VERTEX.y += sign(VERTEX.y) * shape_data.y;
    else if ((mold_flags.z > 1.5 && mold_flags.z < 2.5)) {
        bool cap_vertex = UV.x < 0.0 || UV.x > 1.0;
        if (cap_vertex) {
            float cap_progress = UV.x > 1.0 ? 1.0 : 0.0;
            float cap_angle = shape_data.z + shape_data.w * cap_progress;
            float cap_cos = cos(cap_angle);
            float cap_sin = sin(cap_angle);
            float cap_scale = shape_data.y / MOLD_TORUS_BASE_TUBE_RADIUS;
            float cap_cross_x =
                (VERTEX.x - MOLD_TORUS_BASE_MAJOR_RADIUS) * cap_scale;
            vec3 cap_position = vec3(
                0.5 - shape_data.y + cap_cross_x,
                VERTEX.y * cap_scale,
                0.0);
            VERTEX = vec3(
                cap_position.x * cap_cos - cap_position.z * cap_sin,
                cap_position.y,
                cap_position.x * cap_sin + cap_position.z * cap_cos);
            NORMAL = vec3(
                NORMAL.x * cap_cos - NORMAL.z * cap_sin,
                NORMAL.y,
                NORMAL.x * cap_sin + NORMAL.z * cap_cos);
            UV.x = fract(-cap_angle / MOLD_TAU + 1.0);
            mold_gradient_and_coverage.y = 1.0;
        } else {
            float span = clamp(shape_data.w, 0.0, MOLD_TAU);
            float major_angle = span >= MOLD_TAU
                ? -UV.x * MOLD_TAU
                : shape_data.z + span * (1.0 - UV.x);
            float minor_angle = UV.y * MOLD_TAU;
            vec3 radial = vec3(cos(major_angle), 0.0, sin(major_angle));
            vec3 tube_normal =
                radial * cos(minor_angle) + vec3(0.0, sin(minor_angle), 0.0);
            VERTEX = radial * (0.5 - shape_data.y) + tube_normal * shape_data.y;
            NORMAL = tube_normal;
            if (span < MOLD_TAU)
                UV.x = fract(-major_angle / MOLD_TAU + 1.0);
        }
    }
    mold_line_values.x = 0.0;
    mold_line_values.y = 0.0;
    mold_line_values.z = 0.0;
    mold_line_values.w = 0.0;
    mold_polyline_coord = vec4(0.0);
    if (((int(round(mold_flags.w)) & 4) != 0)) {
        bool local_is_polyline = ((int(round(mold_flags.w)) & 8) != 0);
        bool is_planar_line = (mold_flags.y > 0.5) || local_is_polyline;
        bool local_aa = mold_local_aa_quality() > 0;
        if (is_planar_line) {
            mold_line_values.x = local_is_polyline ? clamp(UV.x, 0.0, 1.0) : UV.x;
            mold_line_values.y = (local_is_polyline ? clamp(UV.y, 0.0, 1.0) : UV.y) * 2.0 - 1.0;
            float padding_pixels = local_aa ? MOLD_AA_PADDING_PIXELS : 0.0;
            if (local_is_polyline) {
                vec2 extrusion = mold_custom0.xy;
                bool is_segment = mold_custom0.z < 0.5;
                float edge_scale = mold_polyline_raster_scale(VERTEX, mold_custom0,
                    mold_custom1, mold_custom2, MODELVIEW_MATRIX, PROJECTION_MATRIX,
                    VIEWPORT_SIZE, padding_pixels, mold_gradient_and_coverage.y);
                VERTEX.xy += extrusion * (edge_scale - 1.0);
                vec4 analytic_coord = mold_custom1;
                vec4 analytic_change = mold_custom2;
                if (is_segment) { analytic_coord.x = 0.0; analytic_change.x = 0.0; }
                mold_polyline_coord = analytic_coord + analytic_change * (edge_scale - 1.0);
                mold_line_values.w = mold_custom0.z;
                mold_line_values.z = mold_polyline_coord.y;
            } else {
                vec3 center_view = (VIEW_MATRIX * MODEL_MATRIX[3]).xyz;
                vec3 length_view = (VIEW_MATRIX * vec4(MODEL_MATRIX[0].xyz, 0.0)).xyz;
                vec3 width_view = (VIEW_MATRIX * vec4(MODEL_MATRIX[1].xyz, 0.0)).xyz;
                vec3 anchor_view = center_view + length_view * (mold_line_values.x - 0.5);
                if (((int(round(mold_flags.w)) & 2) != 0)) {
                    vec3 view_direction = PROJECTION_MATRIX[3][3] > 0.5
                        ? vec3(0.0, 0.0, -1.0) : anchor_view;
                    vec3 side_view = cross(view_direction, length_view);
                    float side_length = length(side_view);
                    if (side_length < 0.00001) {
                        side_view = cross(vec3(0.0, 0.0, -1.0), length_view);
                        side_length = length(side_view);
                    }
                    width_view = (side_length < 0.00001 ? vec3(1.0, 0.0, 0.0)
                        : side_view / side_length) * length(MODEL_MATRIX[1].xyz);
                }
                vec4 anchor_clip = PROJECTION_MATRIX * vec4(anchor_view, 1.0);
                float width_pixels = projected_pixel_distance(anchor_clip,
                    PROJECTION_MATRIX * vec4(anchor_view + width_view, 1.0), VIEWPORT_SIZE);
                mold_gradient_and_coverage.y = width_pixels;
                float length_pixels = projected_pixel_distance(
                    PROJECTION_MATRIX * vec4(center_view - length_view * 0.5, 1.0),
                    PROJECTION_MATRIX * vec4(center_view + length_view * 0.5, 1.0), VIEWPORT_SIZE);
                float width_scale = max(1.0, width_pixels + padding_pixels * 2.0)
                    / max(width_pixels, 0.00001);
            float length_scale = (length_pixels + padding_pixels * 2.0)
                / max(length_pixels, 0.00001);
            mold_line_values.w = (UV.x * 2.0 - 1.0) * length_scale;
            VERTEX.xy *= vec2(length_scale, width_scale);
            UV = (UV - vec2(0.5)) * vec2(length_scale, width_scale) + vec2(0.5);
            mold_line_values.z = mold_line_values.y * width_scale;
            mold_line_values.x = mold_line_values.w * 0.5 + 0.5;
        }
        } else {
            float half_length = (mold_flags.z > 0.5 && mold_flags.z < 1.5) ? max(1.0 + shape_data.y, 0.00001) : 0.5;
            mold_line_values.x = clamp(VERTEX.y / (2.0 * half_length) + 0.5, 0.0, 1.0);
            float raster_scale = mold_spatial_line_raster_scale(mold_line_values.x,
                MODEL_MATRIX, VIEW_MATRIX, PROJECTION_MATRIX, VIEWPORT_SIZE,
                mold_gradient_and_coverage.y);
            VERTEX.xz *= raster_scale;
        }
    }
    if (((int(round(mold_flags.w)) & 2) != 0)) {
        vec3 billboard_center_view = (VIEW_MATRIX * MODEL_MATRIX[3]).xyz;
        vec3 billboard_vertex_view;
        if (((int(round(mold_flags.w)) & 4) != 0)) {
            vec3 billboard_tangent_view = (VIEW_MATRIX * vec4(MODEL_MATRIX[0].xyz, 0.0)).xyz;
            vec3 billboard_centerline_view = billboard_center_view + billboard_tangent_view * VERTEX.x;
            vec3 billboard_view_direction = PROJECTION_MATRIX[3][3] > 0.5
                ? vec3(0.0, 0.0, -1.0)
                : billboard_centerline_view;
            vec3 billboard_side_view = cross(billboard_view_direction, billboard_tangent_view);
            float billboard_side_length = length(billboard_side_view);
            if (billboard_side_length < 0.00001) {
                billboard_side_view = cross(vec3(0.0, 0.0, -1.0), billboard_tangent_view);
                billboard_side_length = length(billboard_side_view);
            }
            billboard_side_view = billboard_side_length < 0.00001
                ? vec3(1.0, 0.0, 0.0)
                : billboard_side_view / billboard_side_length;
            billboard_vertex_view = billboard_centerline_view
                + billboard_side_view * VERTEX.y * length(MODEL_MATRIX[1].xyz);
        } else if (((int(round(mold_flags.w)) & 16) != 0)) {
            vec3 billboard_center_world = MODEL_MATRIX[3].xyz;
            vec3 billboard_facing_world = PROJECTION_MATRIX[3][3] > 0.5
                ? INV_VIEW_MATRIX[2].xyz
                : INV_VIEW_MATRIX[3].xyz - billboard_center_world;
            vec3 billboard_horizontal_world = vec3(
                billboard_facing_world.x, 0.0, billboard_facing_world.z);
            float billboard_horizontal_length = length(billboard_horizontal_world);
            vec3 billboard_right_world;
            if (billboard_horizontal_length < 0.00001) {
                billboard_right_world = vec3(MODEL_MATRIX[0].x, 0.0, MODEL_MATRIX[0].z);
                float billboard_right_length = length(billboard_right_world);
                billboard_right_world = billboard_right_length < 0.00001
                    ? vec3(1.0, 0.0, 0.0)
                    : billboard_right_world / billboard_right_length;
            } else {
                billboard_right_world = cross(
                    vec3(0.0, 1.0, 0.0),
                    billboard_horizontal_world / billboard_horizontal_length);
            }
            vec2 billboard_scale = vec2(
                length(MODEL_MATRIX[0].xyz),
                length(MODEL_MATRIX[1].xyz));
            vec3 billboard_vertex_world = billboard_center_world
                + billboard_right_world * VERTEX.x * billboard_scale.x
                + vec3(0.0, 1.0, 0.0) * VERTEX.y * billboard_scale.y;
            billboard_vertex_view = (VIEW_MATRIX * vec4(billboard_vertex_world, 1.0)).xyz;
        } else {
            vec2 billboard_scale = vec2(
                length(MODEL_MATRIX[0].xyz),
                length(MODEL_MATRIX[1].xyz));
            billboard_vertex_view = billboard_center_view
                + vec3(VERTEX.xy * billboard_scale, 0.0);
        }
        POSITION = PROJECTION_MATRIX * vec4(billboard_vertex_view, 1.0);
    } else {
        POSITION = PROJECTION_MATRIX * MODELVIEW_MATRIX * vec4(VERTEX, 1.0);
    }
 mold_effect_position=VERTEX;
    if (int(round(gradient_data.w)) / 32 >= 100) mold_polyline_coord.xyz = VERTEX;
    mold_gradient_and_coverage.x = 0.0;
    if (packed_gradient(1, 8) == 1 && !((int(round(mold_flags.w)) & 8) != 0)) {
        int shape_kind = int(round(gradient_data.w)) / 32;
        vec3 center = vec3(0.0); vec3 half_extent = vec3(0.5);
        if (shape_kind == 125) { center.y = 0.25; half_extent.y = 0.25; }
        else if (shape_kind == 135) half_extent.y = max(0.0001, 1.0 + shape_data.y);
        else if (shape_kind == 140) half_extent.y = max(0.0001, shape_data.y);
        vec3 local_gradient = packed_gradient(16, 2) == 0 ? transpose(mat3(MODEL_MATRIX)) * gradient_data.xyz : gradient_data.xyz;
        float half_range = max(dot(abs(local_gradient), half_extent), 0.00001);
        mold_gradient_and_coverage.x = clamp(dot((mold_is_billboard ? mold_author_position : VERTEX) - center, local_gradient) / (2.0 * half_range) + 0.5, 0.0, 1.0);
    }
    if (((int(round(mold_flags.w)) & 8) != 0)) mold_gradient_and_coverage.x = mold_line_values.x;

 gl_Position=POSITION;
}
#[fragment]
#version 450
#define MOLD_OIT_MSAA
#define OUTPUT_IS_SRGB false
#define mold_msaa_enabled false
#define FRAGCOORD gl_FragCoord
#define INSTANCE_ID gl_InstanceIndex
#define emission_strength mold_flags.x
#define angular_data lod_data.zw
layout(set=0,binding=0,std430) readonly buffer Vertices { vec4 mesh_data[]; };
layout(set=0,binding=1,std430) readonly buffer Instances { vec4 instance_data[]; };
layout(set=0,binding=2,std140) uniform Camera { mat4 PROJECTION_MATRIX; mat4 VIEW_MATRIX; mat4 INV_VIEW_MATRIX; vec4 viewport; };
#define mold_viewport_size viewport.xy
#define VIEWPORT_SIZE mold_viewport_size

layout(set=0,binding=6,std140) uniform Appearance { vec4 appearance_values[8]; };
#define _PencilAngle appearance_values[0][0]
#define _PencilCrosshatch appearance_values[0][1]
#define _PencilHatchScale appearance_values[0][2]
#define _PencilHatching appearance_values[0][3]
#define _PencilLength appearance_values[1][0]
#define _PencilPaperScale appearance_values[1][1]
#define _PencilPaperSeed appearance_values[1][2]
#define _PencilPressure appearance_values[1][3]
#define _PencilRoughness appearance_values[2][0]
#define _PencilSeed appearance_values[2][1]
#define _PencilSide appearance_values[2][2]
#define _PencilSmudge appearance_values[2][3]
#define _PencilSoftness appearance_values[3][0]
#define _PencilSurfaceScale appearance_values[3][1]
#define _PencilTaper appearance_values[3][2]
#define _PencilPaperColor appearance_values[4]
#define _PencilPaperOrigin appearance_values[5]
#define _PencilPaperU appearance_values[6]
#define _PencilPaperV appearance_values[7]
vec4 primary_color;
vec4 secondary_color;
vec4 shape_data;
vec4 dash_data;
vec4 mold_flags;
vec4 gradient_data;
vec4 lod_data;
layout(location=7) in vec4 mold_line_values;
layout(location=8) in vec2 mold_gradient_and_coverage;
layout(location=9) in vec4 mold_polyline_coord;
layout(location=10) in vec4 mold_vertex_color;
layout(location=11) in vec3 mold_effect_position;
layout(location=0) flat in int oit_instance_id;
layout(location=18) in vec2 UV;

layout(location=0) out vec4 accumulation;
layout(location=1) out float revealage;
#ifndef MOLD_OIT_MSAA
layout(set=0,binding=3) uniform sampler2D scene_depth;
#endif
layout(set=0,binding=4) uniform sampler2D mold_surface_texture;
const float MOLD_TAU = 6.28318530718;
const float MOLD_TORUS_BASE_MAJOR_RADIUS = 0.375;
const float MOLD_TORUS_BASE_TUBE_RADIUS = 0.125;
const float MOLD_AA_PADDING_PIXELS = 1.0;
int bayer_2x2(ivec2 p) {
 return p.x * 2 + p.y * 3 - p.x * p.y * 4;
}
float dither_threshold(vec2 position) {
 ivec2 p = ivec2(position) & ivec2(15);
 int rank = bayer_2x2(p & ivec2(1)) * 64;
 rank += bayer_2x2((p >> 1) & ivec2(1)) * 16;
 rank += bayer_2x2((p >> 2) & ivec2(1)) * 4;
 rank += bayer_2x2((p >> 3) & ivec2(1));
 return float(rank + 1) / 257.0;
}
int mold_local_aa_quality() {
 int flags = int(round(mold_flags.w));
 return (flags & 1) == 0 ? 0 : ((flags & 32) != 0 ? 2 : 1);
}
vec2 mold_ellipse_nearest(vec2 point, vec2 radii) {
 vec2 p = abs(point), r = radii;
 bool swap_axes = r.x < r.y;
 if (swap_axes) { r = r.yx; p = p.yx; }
 float lo = 0.0, hi = 1.5707963267949;
 for (int i=0; i<20; i++) {
  float t=(lo+hi)*0.5, sn=sin(t), cs=cos(t);
  float derivative=(r.y*r.y-r.x*r.x)*sn*cs+r.x*p.x*sn-r.y*p.y*cs;
  if(derivative<0.0) lo=t; else hi=t;
 }
 float t=(lo+hi)*0.5;
 vec2 q=r*vec2(cos(t),sin(t));
 if(swap_axes) q=q.yx;
 q*=vec2(point.x<0.0?-1.0:1.0,point.y<0.0?-1.0:1.0);
 float distance=length(point-q);
 if(length(point/radii)<1.0) distance=-distance;
 return vec2(distance,atan(q.x/radii.x,q.y/radii.y));
}
float mold_partial_derivative(float value) {
 if (mold_local_aa_quality() == 1) return fwidth(value);
 vec2 derivative = vec2(dFdx(value), dFdy(value));
 return length(derivative);
}
float mold_aa(float d) {
 if (mold_local_aa_quality() == 0) return step(d, 0.0);
 float width = max(mold_partial_derivative(d), 0.00001);
 return clamp(0.5 - d / width, 0.0, 1.0);
}
float mold_ellipse_speed(vec2 r,float t) { return length(r*vec2(cos(t),sin(t))); }
float mold_ellipse_integral(vec2 r,float end_angle) {
 float half_angle=end_angle*0.5, total=0.0;
 total+=0.36268378337836*(mold_ellipse_speed(r,half_angle*(1.0-0.18343464249565))+mold_ellipse_speed(r,half_angle*(1.0+0.18343464249565)));
 total+=0.31370664587789*(mold_ellipse_speed(r,half_angle*(1.0-0.52553240991633))+mold_ellipse_speed(r,half_angle*(1.0+0.52553240991633)));
 total+=0.22238103445337*(mold_ellipse_speed(r,half_angle*(1.0-0.79666647741363))+mold_ellipse_speed(r,half_angle*(1.0+0.79666647741363)));
 total+=0.10122853629038*(mold_ellipse_speed(r,half_angle*(1.0-0.96028985649754))+mold_ellipse_speed(r,half_angle*(1.0+0.96028985649754)));
 return half_angle*total;
}
float mold_ellipse_primitive(vec2 r,float angle) {
 float quarter=1.5707963267949;
 float turns=floor(angle/quarter), rest=angle-turns*quarter;
 float full=mold_ellipse_integral(r,quarter);
 return turns*full+(mod(turns,2.0)<0.5 ? mold_ellipse_integral(r,rest) : full-mold_ellipse_integral(r,quarter-rest));
}
float mold_ellipse_progress(vec2 r,float angle,float start,float span) {
 float tau=6.2831853071796;
 start=mod(start,tau);
 float delta=mod(angle-start,tau);
 float base=mold_ellipse_primitive(r,start);
 return (mold_ellipse_primitive(r,start+delta)-base)/max(mold_ellipse_primitive(r,start+span)-base,1e-8);
}
float angular_mask(vec2 p, float start, float span) {
 span = clamp(span, 0.0, MOLD_TAU);
 if (span >= MOLD_TAU - 0.00001) return 1.0;
 if (span <= 0.00001) return 0.0;
 float angle = mod(atan(p.x, p.y) - start + MOLD_TAU * 2.0, MOLD_TAU);
 float delta = abs(mod(angle - span * 0.5 + 3.14159265359, MOLD_TAU) - 3.14159265359);
 return mold_aa((delta - span * 0.5) * max(length(p), 0.00001));
}
float dash_repeat_span(vec4 dash) {
 return dash.x;
}
float dash_shape_type(vec4 dash) {
 float code = dash.y;
 return code < 0.25 ? 0.0 : (code < 0.55 ? 1.0 : 2.0);
}
float dash_shape_modifier(vec4 dash) {
 float type = dash_shape_type(dash);
 float center = 0.1 + type * 0.3;
 return clamp((dash.y - center) / 0.075, -1.0, 1.0);
}
float dash_aa(float signed_distance) {
 if (mold_local_aa_quality() == 0) return step(0.0, signed_distance);
 float width = max(mold_partial_derivative(signed_distance), 0.00001);
 return clamp(signed_distance / width + 0.5, 0.0, 1.0);
}
float dash_segment_mask(float progress, float across, vec4 dash) {
 float total = dash_repeat_span(dash);
 if (total <= 0.0) return 1.0;
 float visible_ratio = 1.0 - clamp(dash.z, 0.0, 1.0);
 if (visible_ratio >= 0.99999) return 1.0;
 across = clamp(across, -1.0, 1.0);
 float type = dash_shape_type(dash);
 float modifier = dash_shape_modifier(dash);
 float coordinate = progress * total + dash.w + (1.0 - visible_ratio) * 0.5;
 float phase_per_across = fwidth(coordinate) / max(fwidth(across), 0.00001);
 if (type < 0.5)
  coordinate += modifier * across * visible_ratio * 0.25;
 else if (type < 1.5)
  coordinate += abs(across) * phase_per_across * modifier;
 float phase = fract(coordinate);
 float half_visible = visible_ratio * 0.5;
 float signed_distance = half_visible - abs(phase - 0.5);
 if (type > 1.5) {
  float cap = clamp(phase_per_across, 0.0, half_visible);
  float profile = sqrt(max(1.0 - across * across, 0.0));
  signed_distance = half_visible - cap * (1.0 - profile) - abs(phase - 0.5);
 }
 return dash_aa(signed_distance);
}
float dashed_mask(float progress, float across, vec4 dash) {
 if (dash_repeat_span(dash) <= 0.0) return 1.0;
 return dash_segment_mask(progress, across, dash);
}
float box_distance(vec2 p) { return max(abs(p.x), abs(p.y)) - 1.0; }
vec2 local_rectangle_extent(float aspect_marker) {
 float aspect = max(-aspect_marker, 0.00001);
 return aspect >= 1.0 ? vec2(aspect, 1.0) : vec2(1.0, 1.0 / aspect);
}
float local_rounded_box_distance(vec2 p, float aspect_marker, float roundness) {
 vec2 extent = local_rectangle_extent(aspect_marker);
 float radius = clamp(roundness, 0.0, 1.0);
 vec2 q = abs(p * extent) - (extent - vec2(radius));
 return length(max(q, vec2(0.0))) + min(max(q.x, q.y), 0.0) - radius;
}
float rounded_box_distance(vec2 p, float roundness) {
 float radius = clamp(roundness, 0.0, 1.0);
 vec2 q = abs(p) - (vec2(1.0) - vec2(radius));
 return length(max(q, vec2(0.0))) + min(max(q.x, q.y), 0.0) - radius;
}
float rectangle_perimeter_progress(vec2 uv, vec2 rim_thickness) {
 vec2 distance_from_outer = min(uv, vec2(1.0) - uv);
 vec2 edge_depth = distance_from_outer / max(rim_thickness, vec2(0.00001));
 vec2 extent = 1.0 / max(rim_thickness, vec2(0.00001));
 float perimeter = max(2.0 * (extent.x + extent.y), 0.00001);
 if (edge_depth.x < edge_depth.y)
  return uv.x < 0.5 ? (2.0 * extent.x + extent.y + (1.0 - uv.y) * extent.y) / perimeter
   : (extent.x + uv.y * extent.y) / perimeter;
 return uv.y < 0.5 ? uv.x * extent.x / perimeter
  : (extent.x + extent.y + (1.0 - uv.x) * extent.x) / perimeter;
}
float rectangle_rim_across(vec2 uv, vec2 rim_thickness) {
 vec2 distance_from_outer = min(uv, vec2(1.0) - uv);
 vec2 edge_depth = distance_from_outer / max(rim_thickness, vec2(0.00001));
 float depth = edge_depth.x < edge_depth.y ? edge_depth.x : edge_depth.y;
 return clamp(depth * 2.0 - 1.0, -1.0, 1.0);
}
float local_rectangle_rim_across(vec2 uv, vec4 shape) {
 vec2 p = uv * 2.0 - 1.0;
 float distance_to_outer = local_rounded_box_distance(p, shape.y, shape.w);
 float thickness = max(shape.z * 2.0, 0.00001);
 return clamp((-distance_to_outer / thickness) * 2.0 - 1.0, -1.0, 1.0);
}
float local_rectangle_rim_coverage(vec2 uv, vec4 shape, vec4 dash) {
 vec2 p = uv * 2.0 - 1.0;
 vec2 extent = local_rectangle_extent(shape.y);
 float distance_to_outer = local_rounded_box_distance(p, shape.y, shape.w);
 float thickness = max(shape.z * 2.0, 0.00001);
 float outer = mold_aa(distance_to_outer);
 float inner = mold_aa(distance_to_outer + thickness);
 vec2 rim = clamp(vec2(shape.z) / extent, vec2(0.00001), vec2(0.5));
 return clamp(outer - inner, 0.0, 1.0) * dashed_mask(
  rectangle_perimeter_progress(uv, rim),
  local_rectangle_rim_across(uv, shape), dash);
}
float angular_progress(vec2 p, float start, float span) {
 span = max(clamp(span, 0.0, MOLD_TAU), 0.00001);
 float angle = mod(atan(p.x, p.y) - start + MOLD_TAU * 2.0, MOLD_TAU);
 return clamp(angle / span, 0.0, 1.0);
}
float disc_rim_rim_across(vec2 p, float thickness) {
 float depth = (1.0 - length(p)) / max(thickness, 0.00001);
 return clamp(depth * 2.0 - 1.0, -1.0, 1.0);
}
float polygon_distance(vec2 p, float sides) {
 float angle = atan(p.x, -p.y);
 float sector = MOLD_TAU / max(sides, 3.0);
 return cos(floor(0.5 + angle / sector) * sector - angle) * length(p) / cos(3.14159265359 / max(sides, 3.0)) - 1.0;
}
float rounded_polygon(vec2 p, float sides, float roundness) {
 roundness = clamp(roundness, 0.0, 1.0);
 if (roundness <= 0.00001) return mold_aa(polygon_distance(p, sides));
 float count = floor(max(abs(sides), 3.0));
 float full_angle = MOLD_TAU / count;
 float half_angle = full_angle * 0.5;
 float diagonal = 1.0 / cos(half_angle);
 float chamfer = max(roundness * half_angle, 0.00001);
 float remaining = half_angle - chamfer;
 float ratio = tan(remaining) / tan(half_angle);
 vec2 center = vec2(cos(half_angle), sin(half_angle)) * ratio * diagonal;
 float distance_a = length(center);
 float distance_b = 1.0 - center.x;
 p *= diagonal;
 vec2 polar = vec2(atan(p.y, p.x), length(p));
 polar.x += 7.85398163397;
 polar.x = abs(mod(polar.x + half_angle, full_angle) - half_angle);
 p = vec2(cos(polar.x), sin(polar.x)) * polar.y;
 float angle_ratio = 1.0 - (polar.x - remaining) / chamfer;
 float distance_c = sqrt(distance_a * distance_a + distance_b * distance_b - 2.0 * distance_a * distance_b * cos(3.14159265359 - half_angle * angle_ratio));
 float normalized = p.x;
 if ((half_angle - polar.x) < chamfer) normalized = polar.y / max(distance_c, 0.00001);
 return mold_aa(normalized - 1.0);
}
float polygon_perimeter_progress(vec2 p, float sides) {
 float angle = atan(p.x, -p.y);
 float count = max(sides, 3.0);
 float sector = MOLD_TAU / count;
 float edge = floor(angle / sector + 0.5);
 float along = tan(angle - edge * sector) / max(tan(sector * 0.5), 0.00001) * 0.5 + 0.5;
 return fract((edge + clamp(along, 0.0, 1.0)) / count);
}
float polygon_rim_across(vec2 p, float sides, float thickness) {
 float depth = -polygon_distance(p, sides) / max(thickness, 0.00001);
 return clamp(depth * 2.0 - 1.0, -1.0, 1.0);
}
float shape_coverage(vec2 uv, vec4 shape, vec4 dash) {
 if (shape.x > 10.5) {
  vec2 radii=shape.yz;
  vec2 point=(uv*2.0-1.0)*(radii+vec2(shape.w));
  vec2 nearest=mold_ellipse_nearest(point,radii);
  float coverage=mold_aa(abs(nearest.x)-shape.w);
  float progress=0.0;
  if(dash.x>0.0) progress=mold_ellipse_progress(radii,nearest.y,lod_data.zw.x,lod_data.zw.y);
  return coverage*angular_mask(point/radii,lod_data.zw.x,lod_data.zw.y)
   *dashed_mask(progress,clamp(-nearest.x/max(shape.w,1e-8),-1.0,1.0),dash);
 }
 float kind = shape.x;
 vec2 p = uv * 2.0 - 1.0;
 float planar_angular = angular_mask(p, lod_data.zw.x, lod_data.zw.y);
 if (kind < 1.5) return mold_aa(box_distance(p)) * planar_angular;
 if (kind < 2.5) return mold_aa(shape.y < 0.0
  ? local_rounded_box_distance(p, shape.y, shape.z)
  : rounded_box_distance(p, shape.z)) * planar_angular;
 if (kind < 3.5) {
  vec2 rim = clamp(vec2(shape.y, shape.z), vec2(0.00001), vec2(0.5));
  float outer = mold_aa(box_distance(p));
  float inner = mold_aa(box_distance(p / max(vec2(1.0) - rim * 2.0, vec2(0.00001))));
  return clamp(outer - inner, 0.0, 1.0) * dashed_mask(rectangle_perimeter_progress(uv, rim), rectangle_rim_across(uv, rim), dash) * planar_angular;
 }
 if (kind < 4.5) {
  if (shape.y < 0.0) return local_rectangle_rim_coverage(uv, shape, dash) * planar_angular;
  vec2 rim = clamp(vec2(shape.y, shape.z), vec2(0.00001), vec2(0.5));
  float outer = mold_aa(rounded_box_distance(p, shape.w));
  vec2 inner_scale = max(vec2(1.0) - rim * 2.0, vec2(0.00001));
  float inner = mold_aa(rounded_box_distance(p / inner_scale, clamp(shape.w / min(inner_scale.x, inner_scale.y), 0.0, 1.0)));
  return clamp(outer - inner, 0.0, 1.0) * dashed_mask(rectangle_perimeter_progress(uv, rim), rectangle_rim_across(uv, rim), dash) * planar_angular;
 }
 if (kind < 5.5) return mold_aa(length(p) - 1.0) * angular_mask(p, shape.y, shape.w);
 if (kind < 6.5) {
  float rim = max(shape.z, 0.00001);
  float coverage = clamp(mold_aa(length(p) - 1.0) - mold_aa(length(p) - max(1.0 - rim, 0.0)), 0.0, 1.0);
  float progress = angular_progress(p, shape.y, shape.w);
  return coverage * angular_mask(p, shape.y, shape.w) * dash_segment_mask(progress, disc_rim_rim_across(p, rim), dash);
 }
 if (kind < 7.5) return mold_aa(polygon_distance(p, shape.y)) * planar_angular;
 if (kind < 8.5) return rounded_polygon(p, shape.y, shape.z) * planar_angular;
 if (kind < 9.5) {
  float outer = mold_aa(polygon_distance(p, shape.y));
  float scale = max(1.0 - shape.z, 0.00001);
  float inner = mold_aa(polygon_distance(p / scale, shape.y));
  return clamp(outer - inner, 0.0, 1.0) * dashed_mask(polygon_perimeter_progress(p, shape.y), polygon_rim_across(p, shape.y, shape.z), dash) * planar_angular;
 }
 float outer = rounded_polygon(p, shape.y, shape.w);
 float scale = max(1.0 - shape.z, 0.00001);
 float inner = rounded_polygon(p / scale, shape.y, clamp(shape.w / scale, 0.0, 1.0));
 return clamp(outer - inner, 0.0, 1.0) * dashed_mask(polygon_perimeter_progress(p, shape.y), polygon_rim_across(p, shape.y, shape.z), dash) * planar_angular;
}
float polyline_pixel_coverage(float edge) {
 vec2 derivative = vec2(dFdx(edge), dFdy(edge));
 return 2.0 / max(length(derivative), 0.00001);
}
float line_local_aa(float coordinate, float pixel_coverage) {
    if (mold_local_aa_quality() == 0) return step(abs(coordinate), 1.0);
 float derivative = max(mold_partial_derivative(coordinate), 0.00001);
 float signed_distance = abs(coordinate) - 1.0;
 float aa_offset = clamp(pixel_coverage / 1.1, 0.0, 1.0) * 0.5;
 return 1.0 - clamp(signed_distance / derivative + aa_offset, 0.0, 1.0);
}
float polyline_cap_aa(float coordinate, float pixel_coverage) {
    if (mold_local_aa_quality() == 0) return step(coordinate, 1.0);
    float derivative = max(mold_partial_derivative(coordinate), 0.00001);
    float offset = clamp(pixel_coverage / 1.1, 0.0, 1.0) * 0.5;
    return 1.0 - clamp((coordinate - 1.0) / derivative + offset, 0.0, 1.0);
}
vec2 mold_evaluate_coverage(vec2 uv, vec2 fragment_position) {
    float lod_threshold = dither_threshold(fragment_position);
    if (lod_data.y > 0.5) lod_threshold = 1.0 - lod_threshold;
    if (lod_data.x < 0.99999 && lod_data.x < lod_threshold) discard;
    bool local_is_line = ((int(round(mold_flags.w)) & 4) != 0);
    bool local_is_polyline = ((int(round(mold_flags.w)) & 8) != 0);
    bool is_planar_line = local_is_line && ((mold_flags.y > 0.5) || local_is_polyline);
    bool rounded_line_2d = is_planar_line && !local_is_polyline
        && shape_data.x > 1.5 && shape_data.x < 2.5;
    bool local_aa = mold_local_aa_quality() > 0;
    float coverage = rounded_line_2d ? shape_coverage(uv, shape_data, dash_data)
        : is_planar_line ? 1.0
        : ((mold_flags.y > 0.5) ? shape_coverage(uv, shape_data, dash_data) : 1.0);
    float thin_line_coverage = 1.0;
    if (local_is_line) {
        vec4 line_dash = dash_data;
        if (!local_is_polyline) coverage *= dashed_mask(mold_line_values.x, mold_line_values.y, line_dash);
        else if (line_dash.x > 0.0) coverage *= line_dash.x >= 1.0 ? 0.0 : dash_aa(1.0-line_dash.x-mold_line_values.x);
        if (is_planar_line) {
            if (local_is_polyline) {
                float edge = mold_line_values.w > 1.5 ? length(mold_polyline_coord.xy) : mold_polyline_coord.y;
                float pixel_coverage = polyline_pixel_coverage(edge);
                thin_line_coverage = clamp(pixel_coverage, 0.0, 1.0);
                if (local_aa) {
                    float outline = line_local_aa(edge, pixel_coverage);
                    float caps = min(polyline_cap_aa(mold_polyline_coord.z, pixel_coverage),
                        polyline_cap_aa(mold_polyline_coord.w, pixel_coverage));
                    coverage *= min(outline, caps);
                } else if (mold_line_values.w > 1.5)
                    coverage *= step(length(mold_polyline_coord.xy), 1.0);
            } else {
                float pixel_coverage = mold_gradient_and_coverage.y;
                thin_line_coverage = clamp(pixel_coverage, 0.0, 1.0);
                if (local_aa && !rounded_line_2d) {
                    coverage *= line_local_aa(mold_line_values.z, pixel_coverage);
                    coverage *= line_local_aa(mold_line_values.w, pixel_coverage);
                } else if (!rounded_line_2d)
                    coverage *= step(abs(mold_line_values.z), 1.0) * step(abs(mold_line_values.w), 1.0);
                coverage *= angular_mask(uv * 2.0 - vec2(1.0), lod_data.zw.x, lod_data.zw.y);
            }
        } else thin_line_coverage = clamp(
            mold_gradient_and_coverage.y, 0.0, 1.0);
    }
    if ((mold_flags.z > 1.5 && mold_flags.z < 2.5)) {
        float span = clamp(shape_data.w, 0.0, MOLD_TAU);
        if (mold_gradient_and_coverage.y > 0.5) {
            if (span <= 0.0 || span >= MOLD_TAU) coverage = 0.0;
        } else if (span <= 0.0) coverage = 0.0;
    }
    return vec2(coverage, thin_line_coverage);
}
int packed_gradient(int divisor, int modulus) {
 return (int(round(gradient_data.w)) / divisor) % modulus;
}
float spatial_color_progress(int color_mode, vec3 p) {
 int kind = int(round(gradient_data.w)) / 32;
 if (color_mode == 4) {
  if (dot(p.xz, p.xz) < 0.0000000001) return 0.0;
  float start = kind == 140 ? shape_data.z : 0.0;
  float span = kind == 140 ? shape_data.w : MOLD_TAU;
  float angle = mod(atan(p.z, p.x) - start + MOLD_TAU * 2.0, MOLD_TAU);
  if (angle > MOLD_TAU - 0.00001) angle = 0.0;
  return clamp(angle / max(span, 0.00001), 0.0, 1.0);
 }
 if (color_mode == 3 && kind == 140) {
  float tube_radius = shape_data.y;
  return clamp((length(p.xz) - (0.5 - 2.0 * tube_radius))
   / max(2.0 * tube_radius, 0.00001), 0.0, 1.0);
 }
 vec3 half_extent = vec3(0.5);
 if (kind == 135) half_extent.y = max(0.00001, 1.0 + shape_data.y);
 else if (kind == 140) half_extent.y = shape_data.y;
 vec3 extent = half_extent * gradient_data.xyz;
 return clamp(length(p * gradient_data.xyz)
  / max(max(extent.x, max(extent.y, extent.z)), 0.00001), 0.0, 1.0);
}
float radial_progress(vec2 uv, vec4 shape, vec2 extent) {
 vec2 p = uv * 2.0 - 1.0; float kind = shape.x;
 if (kind < 4.5 || kind > 6.5) return clamp(length(p * extent) / max(max(extent.x, extent.y), 0.00001), 0.0, 1.0);
 return clamp(length(p), 0.0, 1.0);
}
float radial_bounds_progress(vec2 uv, vec4 shape) {
 if(shape.x>10.5) {
  float d=mold_ellipse_nearest((uv*2.0-1.0)*(shape.yz+vec2(shape.w)),shape.yz).x;
  return clamp(0.5+0.5*d/max(shape.w,1e-8),0.0,1.0);
 }
 vec2 p = uv * 2.0 - 1.0; float kind = shape.x;
 if (kind < 2.5) return clamp(max(abs(p.x), abs(p.y)), 0.0, 1.0);
 if (kind < 4.5) {
  float across = shape.y < 0.0
   ? local_rectangle_rim_across(uv, shape)
   : rectangle_rim_across(uv, vec2(shape.y, shape.z));
  return clamp((1.0 - across) * 0.5, 0.0, 1.0);
 }
 if (kind < 5.5) return clamp(length(p), 0.0, 1.0);
 if (kind < 6.5) return clamp((1.0 - disc_rim_rim_across(p, shape.z)) * 0.5, 0.0, 1.0);
 if (kind < 8.5) return clamp(polygon_distance(p, shape.y) + 1.0, 0.0, 1.0);
 return clamp((1.0 - polygon_rim_across(p, shape.y, shape.z)) * 0.5, 0.0, 1.0);
}
float color_progress(vec2 uv, vec2 extent) {
 int color_mode = packed_gradient(1, 8);
 if (int(round(gradient_data.w)) / 32 >= 100 && color_mode >= 2)
  return spatial_color_progress(color_mode, mold_polyline_coord.xyz);
 if (color_mode == 2) return radial_progress(uv, shape_data, extent);
 if (color_mode == 3) return radial_bounds_progress(uv, shape_data);
 if (color_mode == 4) {
  if (shape_data.x > 10.5) return angular_progress((uv*2.0-1.0)*(shape_data.yz+vec2(shape_data.w))/shape_data.yz, lod_data.zw.x, lod_data.zw.y);
  if (shape_data.x > 4.5 && shape_data.x < 6.5) return angular_progress(uv * 2.0 - 1.0, shape_data.y, shape_data.w);
  if ((shape_data.x > 0.5 && shape_data.x < 4.5) ||
    (shape_data.x > 6.5 && shape_data.x < 10.5))
   return angular_progress(uv * 2.0 - 1.0, lod_data.zw.x, lod_data.zw.y);
  return angular_progress(uv * 2.0 - 1.0, 0.0, MOLD_TAU);
 }
 return mold_gradient_and_coverage.x;
}
vec3 oklab_to_linear(vec3 c) {
 vec3 lms = vec3(c.x + 0.3963377774 * c.y + 0.2158037573 * c.z, c.x - 0.1055613458 * c.y - 0.0638541728 * c.z, c.x - 0.0894841775 * c.y - 1.2914855480 * c.z);
 lms = lms * lms * lms;
 return vec3(4.0767416621 * lms.x - 3.3077115913 * lms.y + 0.2309699292 * lms.z, -1.2684380046 * lms.x + 2.6097574011 * lms.y - 0.3413193965 * lms.z, -0.0041960863 * lms.x - 0.7034186147 * lms.y + 1.7076147010 * lms.z);
}
vec4 evaluated_color(vec2 uv, vec2 extent) {
 if (packed_gradient(1, 8) == 0) return primary_color;
 vec4 result = mix(primary_color, secondary_color, color_progress(uv, extent));
 if (packed_gradient(8, 2) == 1) result.rgb = oklab_to_linear(result.rgb);
 result.rgb *= 1.0 + max(mold_flags.x, 0.0) * 0.12;
 return result;
}
vec4 mold_native_base_color(vec2 uv) {
    return evaluated_color(uv, gradient_data.xy) * mold_vertex_color;
}
vec4 mold_evaluate_base_color(vec2 uv) {
 vec4 color=mold_native_base_color(uv);
 if ((int(round(mold_flags.w)) & 4096) != 0) color *= texture(mold_surface_texture, uv);
 return color;
}
float saturate(float value) { return clamp(value,0.0,1.0); }
float MoldProceduralHash(vec2 p)
{
    vec3 q = fract(vec3(p.xyx) * .1031);
    q += dot(q, q.yzx + 33.33);
    return fract((q.x + q.y) * q.z);
}
float MoldProceduralNoise(vec2 p)
{
    vec2 i = floor(p), f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    return mix(mix(MoldProceduralHash(i), MoldProceduralHash(i + vec2(1,0)), f.x),
        mix(MoldProceduralHash(i + vec2(0,1)), MoldProceduralHash(i + 1.0), f.x), f.y);
}
float PencilTooth(vec2 paper,float pressure)
{
    vec2 p=paper*max(_PencilPaperScale,.001)+_PencilPaperSeed*vec2(3.17,7.93);
    float grain=.25*MoldProceduralNoise(p)+.75*MoldProceduralNoise(p*2.37+19.7);
    float threshold=.66-.48*saturate(pressure);
    float aa=max(fwidth(grain),.025);
    float contact=smoothstep(threshold-aa,threshold+aa,grain)*(.65+.35*grain);
    float footprint=max(length(dFdx(p)),length(dFdy(p)))*2.37;
    return mix(contact,.825*saturate(.12+pressure*.88),smoothstep(.45,1.4,footprint));
}
float PencilNoiseFiltered(vec2 p)
{
    float footprint=max(length(dFdx(p)),length(dFdy(p)));
    return mix(MoldProceduralNoise(p),.5,smoothstep(.4,1.2,footprint));
}
float PencilHatchFamily(vec2 paper,float angle,float pressure,float family)
{
    float sn,cs; sn=sin(angle); cs=cos(angle);
    vec2 p=vec2(cs*paper.x-sn*paper.y,sn*paper.x+cs*paper.y);
    float across=p.y*max(_PencilHatchScale,.01);
    float id=floor(across);
    float seed=MoldProceduralHash(vec2(id,family+_PencilSeed));
    float wobble=.10*sin(p.x*3.0+seed*12.0);
    float distance=abs(fract(across)-(.5+(seed-.5)*.22+wobble));
    float halfWidth=mix(.045,.14,saturate(pressure));
    float aa=max(fwidth(across),.001);
    float hatchMask=1.0-smoothstep(halfWidth-aa,halfWidth+aa,distance);
    float breaks=.7+.3*PencilNoiseFiltered(vec2(p.x*5.0,id+_PencilSeed));
    return mix(hatchMask,2.0*halfWidth,smoothstep(.45,1.3,aa))*breaks;
}
float PencilHatches(vec2 paper,float pressure)
{
    float a=PencilHatchFamily(paper,_PencilAngle,pressure,0);
     if (_PencilCrosshatch <= 0.0) return a;
    float b=PencilHatchFamily(paper,_PencilAngle+1.15,pressure,17)
        *smoothstep(.25,.65,pressure)*_PencilCrosshatch;
    float c=PencilHatchFamily(paper,_PencilAngle+2.05,pressure,37)
        *smoothstep(.65,1.0,pressure)*_PencilCrosshatch;
    return 1.0-(1.0-a)*(1.0-b)*(1.0-c);
}
float PencilDeposit(vec2 paper,float pressure)
{
    float tooth=PencilTooth(paper,pressure);
    float graphite=mix(tooth,.35+.65*tooth,_PencilSmudge);
     if (_PencilHatching <= 0.0) return graphite;
    return graphite*mix(1.0,PencilHatches(paper,pressure),_PencilHatching);
}
void MoldPencilSurface(vec3 localPosition,inout vec4 color,inout float coverage)
{
    float paperAlpha=saturate(_PencilPaperColor.a);
    vec3 localNormal=cross(dFdx(localPosition),dFdy(localPosition));
    localNormal/=max(length(localNormal),1e-12);
    vec3 weights=abs(localNormal)+1e-6;
    weights*=weights; weights*=weights; weights/=dot(weights,vec3(1.0));
    float pressure=saturate(_PencilPressure);
    vec3 p=localPosition*max(_PencilSurfaceScale,.001);
    float deposit=PencilDeposit(p.yz,pressure)*weights.x
        +PencilDeposit(p.zx,pressure)*weights.y+PencilDeposit(p.xy,pressure)*weights.z;
    float graphite=saturate(deposit*pressure);
    float paper=(1.0-graphite)*paperAlpha;
    float alpha=graphite+paper;
    color.rgb=(color.rgb*graphite+_PencilPaperColor.rgb*paper)/max(alpha,1e-6);
    coverage*=alpha;
}
void mold_apply_appearance(vec2 uv, inout vec4 result, inout float coverage) {
 MoldPencilSurface(mold_effect_position,result,coverage);
}
vec4 mold_prepare_output(vec4 result, vec2 coverage_values, vec2 fragment_position) {
    float coverage = coverage_values.x;
    float thin_line_coverage = coverage_values.y;
    if (1 == 4) {
        if (coverage * thin_line_coverage * result.a < dither_threshold(fragment_position)) discard;
        result.a = 1.0;
    } else if (1 == 0) {
        if (false) {
            result.a *= coverage * thin_line_coverage;
            if (result.a <= 0.000001) discard;
        } else {
            if (thin_line_coverage < 0.99999) {
                if (coverage * thin_line_coverage * result.a < dither_threshold(fragment_position)) discard;
            } else if (coverage < 0.5) discard;
            result.a = 1.0;
        }
    } else {
        result.a *= coverage * thin_line_coverage;
        if (result.a <= 0.000001) discard;
    }
    return result;
}
void main() {
 int property_offset=5+int(instance_data[4].x)*3+oit_instance_id*7;
 primary_color=instance_data[property_offset+0];
 secondary_color=instance_data[property_offset+1];
 shape_data=instance_data[property_offset+2];
 dash_data=instance_data[property_offset+3];
 mold_flags=instance_data[property_offset+4];
 gradient_data=instance_data[property_offset+5];
 lod_data=instance_data[property_offset+6];

    vec2 coverage = mold_evaluate_coverage(UV, FRAGCOORD.xy);
    vec4 result = mold_evaluate_base_color(UV);
    mold_apply_appearance(UV, result, coverage.x);
    result = mold_prepare_output(result, coverage, FRAGCOORD.xy);

 // Godot uses reverse Z. Sample opaque depth without changing its attachment.
#ifndef MOLD_OIT_MSAA
 if(gl_FragCoord.z < texelFetch(scene_depth,ivec2(gl_FragCoord.xy),0).r) discard;
#endif
 float a=clamp(result.a,0.0,1.0);
 vec4 view=inverse(PROJECTION_MATRIX)*vec4(0,0,gl_FragCoord.z,1);
 float depth=abs(view.z/view.w);
 float weight=clamp(pow(a+.01,3.0)*32.0/(1.0+depth*.1),.01,32.0);
 accumulation=vec4(result.rgb*a,a)*weight;revealage=a;
}

