// Generated by tools/generate_oit_shader.py. Do not edit.
#[compute]
#version 450
layout(local_size_x=64) in;
layout(set=0,binding=0,std430) readonly buffer Instances { vec4 instance_data[]; };
layout(set=0,binding=1,std140) uniform Camera { mat4 projection; mat4 view; mat4 inverse_view; vec4 viewport; };
layout(set=0,binding=2,std430) writeonly buffer Matrices { mat4 matrices[]; };
void main() {
 uint instance=gl_GlobalInvocationID.x;
 if(instance>=uint(instance_data[4].x)) return;
 uint t=5u+instance*3u;
 vec4 a=instance_data[t],b=instance_data[t+1u],c=instance_data[t+2u];
 mat4 local_matrix=mat4(vec4(a.x,b.x,c.x,0),vec4(a.y,b.y,c.y,0),vec4(a.z,b.z,c.z,0),vec4(a.w,b.w,c.w,1));
 mat4 world=mat4(instance_data[0],instance_data[1],instance_data[2],instance_data[3])*local_matrix;
 matrices[instance*2u]=world;
 matrices[instance*2u+1u]=view*world;
}
