// Generated by tools/generate_oit_shader.py. Do not edit.
#[compute]
#version 450
layout(set=0,binding=0,std430) buffer Meta { uint adaptive_voxel_meta[]; };
layout(set=0,binding=1,std430) buffer Voxels { uint adaptive_voxel_voxels[]; };
layout(set=0,binding=2,std430) buffer Integral { float adaptive_voxel_integral[]; };
layout(set=0,binding=3,std140) uniform Params { vec4 adaptive_voxel_params; };
layout(local_size_x=128) in;

#define ADAPTIVE_VOXEL_BINS 8192u
#define ADAPTIVE_VOXEL_SLICES 128u
#define ADAPTIVE_VOXEL_INFO 16384u
uint adaptive_voxel_width() { return (uint(adaptive_voxel_params.x)+7u)/8u; }
uint adaptive_voxel_height() { return (uint(adaptive_voxel_params.y)+7u)/8u; }
uint adaptive_voxel_cells() { return adaptive_voxel_width()*adaptive_voxel_height(); }
float adaptive_voxel_virtual(float z) { return clamp(log2(1.0+max(z,0.0))*adaptive_voxel_params.z*8191.0,0.0,8191.0); }
// LUT: low 16 bits hold the entry coordinate; flags describe occupied ranges.
#define ADAPTIVE_VOXEL_OCCUPIED 65536u
#define ADAPTIVE_VOXEL_BEGIN 131072u
#define ADAPTIVE_VOXEL_END 262144u
float adaptive_voxel_position(float z) {
 uint used=adaptive_voxel_meta[ADAPTIVE_VOXEL_INFO+1u];
 if(used==0u) return 0.0;
 float v=adaptive_voxel_virtual(z)/float(1u<<adaptive_voxel_meta[ADAPTIVE_VOXEL_INFO]);
 uint b=min(uint(v),(ADAPTIVE_VOXEL_BINS>>adaptive_voxel_meta[ADAPTIVE_VOXEL_INFO])-1u);
 uint entry=adaptive_voxel_meta[ADAPTIVE_VOXEL_BINS+b];
 float p=float(entry&65535u);
 // Empty intervals stay at the preceding range's exit, regardless of gap length.
 // Occupied intervals map their entire [begin,end] interval onto one stored step.
 // Thus both sides of every range boundary agree, including after coarsening.
 if((entry&ADAPTIVE_VOXEL_OCCUPIED)!=0u) p+=fract(v);
 return min(p,float(used-1u));
}

void adaptive_voxel_clear(uint id) {
 if(id<16388u+adaptive_voxel_cells()) adaptive_voxel_meta[id]=0u;
}
void adaptive_voxel_clear_volume(uint cell) {
 uint cells=adaptive_voxel_cells();
 if(cell>=cells || adaptive_voxel_meta[16388u+cell]==0u) return;
 uint used=adaptive_voxel_meta[ADAPTIVE_VOXEL_INFO+1u];
 for(uint z=0u;z<used;z++) adaptive_voxel_voxels[z*cells+cell]=0u;
 adaptive_voxel_voxels[cells*ADAPTIVE_VOXEL_SLICES+cell]=0xffffffffu;
}
// One workgroup compacts the depth bins. Each lane owns 64 consecutive bins;
// coarsening stays local, and only the counts and boundary flags are shared.
shared uint adaptive_voxel_prefix[128];
shared uint adaptive_voxel_first[128];
shared uint adaptive_voxel_last[128];
void adaptive_voxel_map() {
 uint lane=gl_LocalInvocationID.x;
 uint occupied[64];
 for(uint i=0u;i<64u;i++) occupied[i]=min(adaptive_voxel_meta[lane*64u+i],1u);
 uint width=64u, shift=0u, count=0u;
 for(;;) {
  count=0u;
  for(uint i=0u;i<width;i++) count+=occupied[i];
  adaptive_voxel_prefix[lane]=count;
  barrier();
  // Inclusive prefix scan also supplies the total occupancy to every lane.
  for(uint step=1u;step<128u;step<<=1u) {
   uint previous=lane>=step ? adaptive_voxel_prefix[lane-step] : 0u;
   barrier();
   adaptive_voxel_prefix[lane]+=previous;
   barrier();
  }
  if(adaptive_voxel_prefix[127]<=ADAPTIVE_VOXEL_SLICES) break;
  width/=2u; shift++;
  for(uint i=0u;i<width;i++) occupied[i]=occupied[i*2u]|occupied[i*2u+1u];
  barrier();
 }
 adaptive_voxel_first[lane]=occupied[0];
 adaptive_voxel_last[lane]=occupied[width-1u];
 barrier();
 uint index=adaptive_voxel_prefix[lane]-count;
 for(uint i=0u;i<width;i++) {
  uint flags=0u;
  if(occupied[i]!=0u) {
   flags=ADAPTIVE_VOXEL_OCCUPIED;
   uint before=i>0u ? occupied[i-1u] : (lane>0u ? adaptive_voxel_last[lane-1u] : 0u);
   uint after=i+1u<width ? occupied[i+1u] : (lane<127u ? adaptive_voxel_first[lane+1u] : 0u);
   if(before==0u) flags|=ADAPTIVE_VOXEL_BEGIN;
   if(after==0u) flags|=ADAPTIVE_VOXEL_END;
  }
  adaptive_voxel_meta[ADAPTIVE_VOXEL_BINS+lane*width+i]=index|flags;
  index+=occupied[i];
 }
 if(lane==0u) {
  adaptive_voxel_meta[ADAPTIVE_VOXEL_INFO]=shift;
  adaptive_voxel_meta[ADAPTIVE_VOXEL_INFO+1u]=adaptive_voxel_prefix[127];
 }
}
void adaptive_voxel_integrate(uint cell) {
 uint cells=adaptive_voxel_cells(); if(cell>=cells) return;
 if(adaptive_voxel_meta[16388u+cell]==0u) return;
 float sum=0.0; uint overflow=adaptive_voxel_voxels[cells*ADAPTIVE_VOXEL_SLICES+cell];
 for(uint z=0u;z<adaptive_voxel_meta[ADAPTIVE_VOXEL_INFO+1u];z++) {
  if(sum<32.0) sum=min(32.0,sum+float(adaptive_voxel_voxels[z*cells+cell])/65536.0);
  if(z>=overflow) sum=32.0;
  adaptive_voxel_integral[z*cells+cell]=sum;
 }
}

void main(){adaptive_voxel_map();}
