// Generated by tools/generate_oit_shader.py. Do not edit.
#[vertex]
#version 450
void main(){gl_Position=vec4(vec2((gl_VertexIndex<<1)&2,gl_VertexIndex&2)*2.0-1.0,0,1);}

#[fragment]
#version 450
layout(set=0,binding=0) uniform sampler2DMS accum;
layout(set=0,binding=1) uniform sampler2DMS reveal;
layout(location=0) out vec4 color;
layout(push_constant,std430) uniform Params { vec4 values; } params;
void main(){
 ivec2 p=ivec2(gl_FragCoord.xy);
 vec4 a=texelFetch(accum,p,gl_SampleID);
 float opacity=1.0-clamp(texelFetch(reveal,p,gl_SampleID).r,0.0,1.0);
 color=vec4(a.rgb/max(a.a,1e-6)*opacity*params.values.x,opacity);
}
